INSERT INTO typeRelation(idTypeRelation,nameRelation) VALUES (0,'SON'),(1,'DAUGHTER'),(2,'BROTHER'),(3,'SISTERR'),(4,'MOTHER')
,(5,'FATHER'),(6,'GRAMPA'),(7,'GRANDMOTHER'),(8,'GREATE_GRANDMOTHER'),(9,'GREAT_GRANDFATHER'),(10,'UNCLE'),(11,'AUNT'),(12,'GRANDCHILD')
,(13,'COUSIN'),(14,'SON_IN_LAW'),(15,'FATHER_IN_LAW'),(16,'WIFE'),(17,'HUSBAND'),(18,'FRIEND'),(19,'GIRL_FRIEND'),(20,'BOY_FRIEND')
,(21,'COLLEAGUE'),(22,'BOSS');